### PR TITLE
fixed: dropping hierarchy item on pseudo scene creates duplicates

### PR DESCRIPTION
**Pull request by iXtenda**
How to replicate the issue:

1. Create a runtime hierarchy with a pseudo scene
2. Add 2 GameObjects to the pseudo scene
3. In the runtime hierarchy, drag one of the displayed items onto the other one to create a child
4. Drag the child back on the pseudo scene

Result:
The hierarchy displays the dragged item twice, because the Transform is added to the pseudo scene, but not re-parented. This also happens when moving items between pseudo scenes.

### CODE REVIEW

**Comment by yasirkula** [comment]
Changing an object's parent when it is dropped onto a pseudo scene is not something I like because pseudo scenes aren't tied to any Transform. By default, adding Transforms to pseudo scenes isn't even allowed. When it is allowed by enabling "Can Add Objects To Pseudo Scenes" option of "Hierarchy Drag Drop Listener", duplicate root entries are still not allowed. No matter how many times I drop object A onto pseudo-scene B, object A is added to the pseudo scene only once. So there aren't any duplicates created.

**Comment by iXtenda** [comment]
Maybe we could find a different solution then. What do you think should happen when de-parenting inside a pseudo scene? Having the object as a child of another object in the pseudo-scene **and** as a root object in the pseudo-scene at the same time seems weird to me.

**Comment by yasirkula** [comment]
I'm actually happy with that 😄 The current state is as straightforward and bug-free as it can get.

**Comment by iXtenda** [comment]
Just to avoid miscommunication, this is the behavior I'm referring to: 

DragDrop

**Comment by yasirkula** [comment]
Yes, I know. It is allowed to have both _GameObject (1)_ and _GameObject (3)_ in the same pseudo-scene and I am happy with this behaviour.

**Comment by iXtenda** [comment]
Alright, thanks for the clarification 👍 
 I'll close the PR then.

**Pull request closed without merging**
