### PR TITLE
Feature: Scene filter

### PR DESCRIPTION
**Pull request by iXtenda**
Added the ability to filter which scenes are exposed to the hierarchy.

### CODE REVIEW

**Comment by yasirkula** [comment]
When I set the value of _Exposed Scenes_, does it prevent _Dont Destroy On Load_ scene from being exposed unless I add it manually to the list?

**Comment by iXtenda** [comment]
In the current implementation it does, but I guess it would make sense not to do so. From my perspective _Dont Destroy On Load_ is a special case and should be solely controlled by `m_exposeDontDestroyOnLoadScene`. I could easily update the PR. All that would be necessary is to change this line

```cs
if( !ExposeUnityScenes || (exposedScenes != null && exposedScenes.Length > 0 && System.Array.IndexOf(exposedScenes, arg0.name) == -1) )
```

to this

```cs
if( !ExposeUnityScenes || arg0.buildIndex < 0 || (exposedScenes != null && exposedScenes.Length > 0 && System.Array.IndexOf(exposedScenes, arg0.name) == -1) )
```
_Dont Destroy On Load_ has a build index of -1, which Unity does not allow for user created scenes, so we would just exclude all "Unity reserved scenes". Alternatively we could of course compare the scenes name, but that wouln't be my preferred solution.

**Comment by iXtenda** [comment]
Alright, I've updated the PR according to my proposed solution. If you prefer a different solution, just let me know.

**Comment by iXtenda** [comment]
I've implemented the requested changes. Should be fine now.

**Review by yasirkula — APPROVED** [review]

**Comment by yasirkula** [comment]
Thanks for the changes. I'll merge this PR as soon as possible. Sorry for the delay.

**Comment by iXtenda** [comment]
No, worries. Thanks for accepting the PR.

**Pull request merged**
